### ISSUE TITLE
Make includes more optional

### ISSUE THREAD

**Issue by jardleex** [mrlesmithjr/ansible-docker#14]
Hi @mrlesmithjr ,

now I'll capture your next role *g*...

I'd like to put in switches to make the include/installation of 
- `manage_python_modules.yml` 
- `linux-image-extra-{{ ansible_kernel }}`
- `bridge-utils`

optional to the role user. For most of our use cases we won't need these tools and like to opt-out of their installation.

What do you think?

**Comment by mrlesmithjr** [comment]
@jardleex Glad you are here dude! I think this makes complete sense.
